.github/workflows/security.yaml
=> Add Workflow call

.github/workflows/ci-backend.yaml
=> Workflow CI call

.github/workflows/ci-backend.yaml
=> Bump node version

.github/workflows/ci-backend.yaml
=> Read secret from env var

.github/workflows/ci-backend.yaml
- Change workflow to pick up version from `.nvmrc`
=> CI action update

.github/workflows/publish-package.yaml
- Create workflow for publishing a package
=> Publish package action

.github/workflows/publish-package.yaml
=> Add working DIR and if present check to lint

.github/workflows/publish-package.yaml
=> Publish GH event input

.github/workflows/publish-package.yaml
=> Move working DIR

.github/workflows/publish-package.yaml
=> Refactor to inputs syntax

.github/workflows/publish-package.yaml
=> Enable publishing

.github/workflows/publish-package.yaml
=> If syntax change

.github/workflows/cache-cleanup.yaml
=> feat(): Cache cleanup action

.github/workflows/ci-backend.yaml
- Update workflow to take in optional flag
=> feat(ci): add optional input 'dynamodb' for integration tests

.github/workflows/ci-backend.yaml
- Update to refernce as boolean
=> DyanmoDB syntax to turn off step

.github/workflows/deploy-backend.yaml, package-lock.json, package.json
- Read service-name from `package.json`
- Add descriptions to inputs
- Update package.json depdendecy
=> Deploy - Read service from package.json

.github/workflows/ci-backend.yaml
=> build(ci-backend): add packaging and artefact summary to workflow

.github/workflows/cache-cleanup.yaml, .github/workflows/ci-backend.yaml, .github/workflows/deploy-backend.yaml, .github/workflows/publish-package.yaml
=> Update checkout to v4

.github/workflows/release-manifest.yaml
amend branch to point to main branch of workflow repo
Related issue: [MES-9153](https://dvsa.atlassian.net/browse/MES-9153)
=> amend branch to point to main branch of workflow repo

.github/workflows/manage-nonprod-rds-clusters.yaml
add workflow for managing nonprod RDS clusters to test
=> add workflow for managing nonprod RDS clusters to test

.github/workflows/manage-nonprod-rds-clusters.yaml
=> Mes 9505 rds cluster workflow

.github/actions/nonprod-rds-management/action.yaml, .github/workflows/manage-nonprod-rds-clusters.yaml
=> add composite action

.github/workflows/manage-nonprod-rds-clusters.yaml
add aws commands for starting and stopping clusters
=> add aws commands for starting and stopping clusters

.github/workflows/build-mobile-app-config.yaml
Add workflow for building mobile app config file
Related issue: [MES-9532](https://dvsa.atlassian.net/browse/MES-9532)
=> Mes 9532 mobile config workflow

.github/workflows/run-mobile-app-automation.yaml
Migrate mobile app automation pipeline from Jenkins to GHA
Related issue: [MES-9543](https://dvsa.atlassian.net/browse/MES-9543)
=> Mes 9543 mobile automation

.github/workflows/run-mobile-app-automation.yaml
add missing cp command for aws
Related issue: [MES-9543](https://dvsa.atlassian.net/browse/MES-9543)
=> add missing cp command for aws

.github/workflows/build-mobile-app-config.yaml, .github/workflows/cache-cleanup.yaml, .github/workflows/ci-backend.yaml, .github/workflows/deploy-backend.yaml, .github/workflows/manage-nonprod-rds-clusters.yaml, .github/workflows/publish-package.yaml, .github/workflows/release-manifest.yaml, .github/workflows/run-mobile-app-automation.yaml, .github/workflows/security.yaml, README.md
update readme; add emojis in workflow names
Related issue: [MES-9622](https://dvsa.atlassian.net/browse/MES-9622)
=> update readme; add emojis in workflow names

.github/workflows/run-mobile-app-automation.yaml
Amend mobile app automation reusable workflow to enable deploying the report to GitHub Pages with report history.
Related issue: [MES-9543](https://dvsa.atlassian.net/browse/MES-9543)
=> Mes 9543 mobile automation amendment

.github/workflows/manage-nonprod-rds-clusters.yaml
correct send teams notification action version
=> correct send teams notification action version

.github/actions/get-tfvars/action.yaml, .github/actions/terraform-apply/action.yaml, .github/actions/terraform-plan/action.yaml, .github/workflows/terraform-plan.yaml
add terraform plan reusable workflow
=> add terraform plan reusable workflow

.github/workflows/terraform-plan.yaml
=> add ref for tf actions

.github/workflows/manage-nonprod-rds-clusters.yaml
correct sed command for updating exclusion list
=> correct sed command for updating exclusion list

.github/workflows/terraform-deploy.yaml, .github/workflows/terraform-plan.yaml
Mes 9323 terraform apply workflows
=> Mes 9323 terraform apply workflows

.github/workflows/terraform-plan.yaml
correct the component input name
=> correct the component input name

.github/workflows/terraform-plan.yaml
bump upload-artifact to version 4
=> bump upload-artifact to version 4

.github/workflows/terraform-action.yaml
correct reference to tfvars for plan/apply step
=> correct reference to tfvars for plan/apply step

.github/workflows/terraform-action.yaml
=> correct aws region variable

.github/workflows/terraform-deploy.yaml
correct variable name for the input component
=> correct variable name for the input component

.github/workflows/terraform-action.yaml, .github/workflows/terraform-deploy.yaml
rename reusable workflow jobs depending on tf-action
=> rename reusable workflow jobs depending on tf-action

.github/actions/db-functions/run-create-user-script/action.yaml, .github/workflows/full-dms-deploy.yaml, .github/workflows/terraform-action.yaml, .github/workflows/terraform-deploy.yaml
add changes for debugging TF workflows
=> add changes for debugging TF workflows

.github/workflows/manage-gha-tf-runner.yaml
=> amend typo

.github/workflows/full-dms-deploy.yaml
add runner input for full dms deploy workflow
Related issue: [JIRA_TICKET_NUMBER](https://dvsa.atlassian.net/browse/MES-9323)
=> add runner input for full dms deploy workflow

.github/workflows/manage-gha-tf-runner.yaml
correct inputs for aws-github-runner action
=> correct inputs for aws-github-runner action

.github/workflows/manage-gha-tf-runner.yaml
correct the ec2-instance-id input
=> correct the ec2-instance-id input

.github/workflows/manage-gha-tf-runner.yaml
split start and stop runner into separate steps
=> split start and stop runner into separate steps

.github/workflows/full-dms-deploy.yaml
change all full DMS deploy inputs to required; correct usage of ec2 runner
=> MES-9323-fix-inputs

.github/workflows/full-dms-deploy.yaml
remove ec2 runner setup/setdown and workflow_dispatch
=> MES-9323 - remove ec2 runner setup/setdown and workflow_dispatch

.github/actions/dms-functions/invoke-lambda-function/action.yaml
correct invoke-lambda-function action input usage
=> MES-9323 - correct invoke-lambda-function action input usage

.github/actions/db-functions/run-db-script/action.yaml, .github/workflows/full-dms-deploy.yaml
update run db script action to enable execution of single file and accept db-username as input
=> MES-9323 update run db script action

.github/actions/db-functions/run-db-script/action.yaml
=> MES-9323 correct input names

.github/workflows/full-dms-deploy.yaml
correct usage of RDS_CREDENTIALS env secrets
=> MES-9323 correct usage of RDS_CREDENTIALS env secrets

.github/actions/db-functions/run-db-script/action.yaml
remove space from mysql p flag
=> MES-9323 remove space from mysql p flag

.github/actions/db-functions/run-db-script/action.yaml
change method of calling mysql scripts
=> MES-9323 - change method of calling mysql scripts

.github/workflows/full-dms-deploy.yaml
=> MES-9323 - add missing escape new line

.github/workflows/full-dms-deploy.yaml
=> MES-9323- amend get DMS tasks step

.github/actions/dms-functions/stop-dms-task/action.yaml, .github/actions/dms-functions/wait-until-task-complete/action.yaml
=> MES-9323 - refactor dms functions

.github/workflows/terraform-deploy.yaml
amend job index input to not required
=> MES-9323 - amend job index input to not required

.github/workflows/terraform-action.yaml
add environment if action is apply to terraform action workflow
=> MES-9323 - add environment if action is apply to terraform action workflow

.github/workflows/terraform-action.yaml
correct use of tf-action input
=> MES-9323 - correct use of tf-action input

.github/workflows/terraform-action.yaml
set filename in terraform show step
=> MES-9323 - set filename in terraform show step

.github/workflows/terraform-action.yaml
fix set filename section; add emojis to workflow name
=> MES-9323 - fix set filename section

.github/workflows/terraform-action.yaml, .github/workflows/terraform-deploy.yaml
Make the Terraform deploy workflow reusable across dev, perf, uat, prep, and prod. 
=> Mes 9323 - terraform apply workflows amendments

.github/workflows/terraform-action.yaml
=> MES-9323 - fix typo

.github/workflows/full-dms-deploy.yaml, .github/workflows/manage-gha-tf-runner.yaml, .github/workflows/terraform-action.yaml, .github/workflows/terraform-deploy.yaml
add aws-account-id input; update inputs for start ec2 runner action
=> MES-9323 - add aws-account-id input; update inputs for start ec2 runner action

.github/workflows/full-dms-deploy.yaml, .github/workflows/manage-gha-tf-runner.yaml, .github/workflows/terraform-action.yaml, .github/workflows/terraform-deploy.yaml
revert aws-account-id input addition
=> MES-9323 - revert aws-account-id input addition

.github/workflows/terraform-action.yaml
bump setup-terraform action version
=> MES-9323 - bump setup-terraform action version

.github/actions/setup-node/action.yaml, .github/workflows/ci-backend.yaml, .github/workflows/publish-package.yaml
bump setup-node action version to v4
Related issue: [MES-9845](https://dvsa.atlassian.net/browse/MES-9845)
=> MES-9845 - bump setup-node action version to v4

.github/actions/setup-node/action.yaml
remove cache option from setup-node action
Related issue: [MES-9845](https://dvsa.atlassian.net/browse/MES-9845)
=> MES-9845 - remove cache option from setup-node action

.github/workflows/terraform-deploy-personal.yaml
add personal env terraform deploy workflow
=> Mes 9843 personal env workflow

.github/workflows/terraform-deploy-personal.yaml
correct shorthand if statement
=> MES-9843 - correct shorthand if statement

.github/workflows/run-mobile-app-automation.yaml
add job in automation workflow to cleanup gh-pages branch; add job names
=> add job in automation workflow to cleanup gh-pages branch; add job names

.github/workflows/run-mobile-app-automation.yaml
add step to push the cleanup of old reports to remote
=> add step to push the cleanup of old reports to remote

.github/workflows/run-mobile-app-automation.yaml
corrects needs context for final job
=> corrects needs context for final job

.github/workflows/terraform-deploy-personal.yaml
fix if statement for determine if first run and add region as secret
=> MES-9843 - fix if statement for determine if first run and add region as secret

.github/workflows/terraform-deploy-personal.yaml
=> MES-9843 - fix results-db repo name

.github/workflows/terraform-deploy-personal.yaml
=> MES-9843 - fix result-db branch name

.github/workflows/terraform-deploy-personal.yaml
fix service_name variable evaluating if first run is taking place
=> MES-9843 - fix service_name variable evaluating if first run is taking place

.github/workflows/terraform-deploy-personal.yaml
fix ability to destroy personal env
=> MES-9843 - fix ability to destroy personal env

.github/workflows/terraform-deploy-personal.yaml
correct matrix tf-action so that it plans a destroy if tf action is destroy
=> MES-9843 - correct matrix tf-action

.github/workflows/terraform-deploy-personal.yaml
correct needs context for subsequent jobs
=> correct needs context for subsequent jobs

.github/workflows/terraform-action.yaml
update terraform action workflow to upload plan for a plan-destroy
=> MES-9843 - update terraform action workflow to upload plan for a plan-destroy

.github/workflows/terraform-deploy-personal.yaml
add missing key for results db set up; fix job results db setup and dynamodb setup job conditional
=> MES-9843 - add missing key for results db set up

.github/workflows/manage-gha-tf-runner.yaml, .github/workflows/terraform-deploy-personal.yaml
add tars replica setup for personal env; add git installation for GHA runner
=> MES-9843 - add tars replica setup for personal env

.github/workflows/terraform-action.yaml
fix missing plan-destroy checks
=> MES-9843 - fix missing plan-destroy checks

.github/workflows/terraform-deploy-personal.yaml
fix inputs for running db script steps
=> MES-9843 - fix inputs for running db script steps

.github/workflows/terraform-deploy-personal.yaml
correct set terraform args step
=> MES-9843 - correct set terraform args step

.github/workflows/terraform-deploy.yaml
update create db users job to assume creds in nonprod or prod account
Related issue: MES-9860
=> MES-9860 - update create db users job to assume creds in nonprod or prod account

.github/workflows/release-manifest.yaml
fix ms teams notification failing
Related issue: [MES-9883](https://dvsa.atlassian.net/browse/MES-9883)
=> MES-9883 - fix ms teams notification failing

.github/workflows/build-squidnat-artifacts.yaml
add reusable workflow for building squidnat config/cert
=> MES-9886 - add reusable workflow for building squidnat config/cert

.github/workflows/build-squidnat-artefacts.yaml, .github/workflows/deploy-backend.yaml, .github/workflows/terraform-action.yaml, .github/workflows/terraform-deploy-personal.yaml, .github/workflows/terraform-deploy.yaml
rename artifact to artefact to ensure consistency
=> MES-9886 - rename artifact to artefact

.github/workflows/build-squidnat-artefacts.yaml
add needs determine-matrix for build-squinat-artefact job
=> add needs determine-matrix for build-squinat-artefact job

.github/workflows/build-squidnat-artefacts.yaml
fix certificate artifact file name
=> MES-9886 - fix certificate artifact file name

.github/workflows/build-squidnat-artefacts.yaml
fetch all commits for checkout action so that build script runs as expected
=> MES-9886: fetch all commits for checkout action

.github/workflows/build-ami.yaml
add wip build ami workflow
Related issue: [MES-9894](https://dvsa.atlassian.net/browse/MES-9894)
=> MES-9894: add wip build ami workflow

.github/workflows/build-ami.yaml, .github/workflows/manage-gha-tf-runner.yaml, .github/workflows/terraform-deploy-personal.yaml, .github/workflows/terraform-deploy.yaml
Finalise build-ami workflow & update TF workflows to specify manage-gha-tf-runner secrets
Related issue: [MES-9894](https://dvsa.atlassian.net/browse/MES-9894)
=> Mes 9894 packer workflow

.github/workflows/build-ami.yaml
add HOME env to enable ssh key to be found
Related issue: [MES-9894](https://dvsa.atlassian.net/browse/MES-9894)
=> add HOME env to enable ssh key to be found

.github/workflows/build-ami.yaml
update github summary message
Related issue: [MES-9894](https://dvsa.atlassian.net/browse/MES-9894)
=> MES-9894: update github summary message

.github/workflows/manage-gha-tf-runner.yaml
remove pre-runner-script input
Related issue: [MES-9900](https://dvsa.atlassian.net/browse/MES-9900)
=> MES-9900: remove pre-runner-script input

.github/workflows/build-ami.yaml, .github/workflows/manage-gha-tf-runner.yaml
add pre-runner-script to build-ami workflow
Related issue: [MES-9900](https://dvsa.atlassian.net/browse/MES-9900)
=> MES-9900: add pre-runner-script to build-ami workflow

.github/workflows/deploy-backend.yaml
remove sonar-scan job from deploy-backend workflow
Related issue: [MES-9910](https://dvsa.atlassian.net/browse/MES-9910)
=> MES-9910: remove sonar-scan job from deploy-backend workflow

.github/workflows/terraform-full-deploy.yaml
add workflow to destroy/apply environment from scratch
=> MES-9903: add workflow to destroy/apply environment from scratch

.github/workflows/terraform-full-deploy.yaml
amend full env deploy workflow
=> MES-9903: amend full env deploy workflow

.github/workflows/terraform-full-deploy.yaml
=> MES-9903: update needs

.github/workflows/deploy-backend.yaml
add conditional to enable mot service to use the workflow
Related issue: [MES-9884](https://dvsa.atlassian.net/browse/MES-9884)
=> add conditional to enable mot service to use the workflow

.github/workflows/terraform-full-deploy.yaml
add step in full deploy workflow to run DMS task updater lambda
=> MES-9903: add step in full deploy workflow to run DMS task updater lambda

.github/workflows/terraform-full-deploy.yaml
remove full DMS deploy jobs and fix name
=> MES-9903: remove full DMS deploy jobs and fix name

.github/workflows/terraform-full-deploy.yaml
add check for rds cluster state for destroy run; fix job names
=> MES-9903: add check for rds cluster state for destroy run; fix job names

README.md
update readme to include new reusable workflows
Related issue: [MES-9989](https://dvsa.atlassian.net/browse/MES-9989)
=> MES-9989: update readme to include new reusable workflows

.github/workflows/run-prowler.yaml
add wip prowler workflow
Related issue: [MES-10070](https://dvsa.atlassian.net/browse/MES-10070)
=> MES-10070: add wip prowler workflow

.github/workflows/run-prowler.yaml
Finalise reusable workflow for prowler 
Related issue: [MES-10070](https://dvsa.atlassian.net/browse/MES-10070)
=> MES-10070: update prowler wf

.github/scripts/update-des-app-version.js, .github/workflows/build-mobile-app-wip.yaml
new wip workflow for fastlane update
=> Mes 10040: new wip workflow for fastlane update

.github/workflows/build-mobile-app-wip.yaml
=> MES-10040: correct use of sentry script

.github/workflows/build-mobile-app-wip.yaml
=> MES-10040: add fastlane env as secrets

.github/workflows/build-mobile-app-wip.yaml
=> MES-10040: add pod install step

.github/workflows/build-mobile-app-wip.yaml
=> MES-10040: remove des-globals secrets

.github/workflows/build-mobile-app-wip.yaml
=> MES-10040: add xcode version option

.github/workflows/build-mobile-app-wip.yaml
retrieve fast-config with cli command
=> MES-10040: retrieve fast-config with cli command

.github/workflows/build-mobile-app-wip.yaml
=> MES-10040: fix syntax

.github/workflows/build-ami.yaml, .github/workflows/build-mobile-app-config.yaml, .github/workflows/build-squidnat-artefacts.yaml, .github/workflows/manage-nonprod-rds-clusters.yaml
update workflows so that we can call from des-devops repo
=> MES-10074: update workflows so that we can call from des-devops repo

.github/workflows/manage-nonprod-rds-clusters.yaml
=> MES-10074: remove run-name

.github/workflows/build-mobile-app-config.yaml, .github/workflows/manage-nonprod-rds-clusters.yaml, .github/workflows/terraform-deploy-personal.yaml, .github/workflows/terraform-full-deploy.yaml
=> MES-10074: correct aws role secret names

.github/actions/db-functions/run-db-script/action.yaml, .github/workflows/terraform-deploy-personal.yaml
replace ssh-key with token; point to working branch for data-poller-service init result db job
=> MES-10074: replace ssh-key with token; point to working branch

.github/workflows/build-ami.yaml
update checkout packer repo step
=> MES-10074: update checkout packer repo step

.github/actions/db-functions/run-db-script/action.yaml
amend token alternate input for db functions checkout
=> MES-10074: amend token alternate input for db functions checkout

.github/workflows/terraform-deploy-personal.yaml
=> MES-10074: update initialise tars branch

.github/workflows/terraform-deploy-personal.yaml
update remaining python commands
=> MES-10074: update remaining python commands

.github/workflows/build-mobile-app.yaml
=> MES-10074: update sentry deploy command

.github/workflows/deploy-backend-des.yaml, .github/workflows/deploy-backend-new.yaml
Add deploy workflow to be called from backend microservices repositories created from the new repo template. 
Related issue: [MES-9939](https://dvsa.atlassian.net/browse/MES-9939)
=> Mes 9939: new micro service deploy template

.github/workflows/undo-release-cut.yaml
fix typo
Related issue: [MES-10102](https://dvsa.atlassian.net/browse/MES-10102)
=> MES-10102: fix typo

.github/workflows/build-mobile-app.yaml
remove xcode version input
Related issue: [MES-10152](https://dvsa.atlassian.net/browse/MES-10152)
=> MES-10152: remove xcode version input

.github/workflows/build-mobile-app.yaml
- updated method of generating npmrc and ionic config to ensure secrets are masked
- added steps to enable retrieval of the generated artefact from the Teams channel
Related issue: [MES-10160](https://dvsa.atlassian.net/browse/MES-10160)
=> MES-10160: mobile app wf updates

.github/actions/generate-ms-teams-json/action.yaml, .github/workflows/ci-backend.yaml, .github/workflows/deploy-backend-des.yaml, .github/workflows/release-manifest-des.yaml
add release manifest wf for new backend repo template; add ability to use the input branch or the github ref name
Related issue: [MES-10158](https://dvsa.atlassian.net/browse/MES-10158)
=> MES-10158: add release manifest wf for new backend repo template

.github/workflows/build-mobile-app.yaml
Fix ipa naming step
Related issue: [MES-10214](https://dvsa.atlassian.net/browse/MES-10214)
=> MES-10214: fix ipa naming step

.github/workflows/terraform-action.yaml, .github/workflows/terraform-deploy.yaml
Update Terraform deploy workflow to enable targeted deployments of single components; remove drs-early-run input; amend Terraform action workflow comments
Related issue: [MES-10232](https://dvsa.atlassian.net/browse/MES-10232)
=> MES-10232: Terraform GHA workflow improvements

.github/workflows/ci-backend.yaml
revert branch input change to ci-backend.yaml
Related issue: [MES-10158](https://dvsa.atlassian.net/browse/MES-10158)
=> MES-10158: revert branch input change to ci-backend.yaml

.github/workflows/ci-backend.yaml, .github/workflows/deploy-backend.yaml
update upload/download artifact action to version 4
Related issue: [MES-10233](https://dvsa.atlassian.net/browse/MES-10233)
=> MES-10233: update upload/download artifact action to version 4

.github/workflows/deploy-backend-des.yaml
correct lambda_function_name for deploy workflow
Related issue: [MES-10158](https://dvsa.atlassian.net/browse/MES-10158)
[MES-10158]: https://dvsa.atlassian.net/browse/MES-10158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10158: correct lambda_function_name for deploy workflow

.github/workflows/deploy-backend-des.yaml, .github/workflows/deploy-backend.yaml
correct MS Teams webhook for service builds
Related issue: [MES-10158](https://dvsa.atlassian.net/browse/MES-10158)
[MES-10158]: https://dvsa.atlassian.net/browse/MES-10158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10158: correct MS Teams webhook for service builds

.github/workflows/deploy-backend.yaml
fix msteams notification for deploy backend workflow
=> fix msteams notification for deploy backend workflow

.github/actions/dms-functions/wait-for-replication-task/action.yaml, .github/workflows/full-dms-deploy.yaml
minor corrections to full DMS process workflow
Related issue: [MES-10262](https://dvsa.atlassian.net/browse/MES-10262)
[MES-10262]: https://dvsa.atlassian.net/browse/MES-10262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10262: minor corrections to full DMS process workflow

.github/workflows/full-dms-deploy.yaml
correct the final step in full DMS deploy workflow
Related issue: [MES-10262](https://dvsa.atlassian.net/browse/MES-10262)
[MES-10262]: https://dvsa.atlassian.net/browse/MES-10262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10262: correct the final step in full DMS deploy workflow

.github/workflows/ci.yaml
=> add ci workflow for testing

.github/workflows/ci.yaml
=> add repo to checkout step

.github/workflows/build-mobile-app.yaml
Use github.ref_name instead of branch
Simplify retrieval of artefact URLs 
Improve MS teams notification readability
Related issue: [MES-10320](https://dvsa.atlassian.net/browse/MES-10320)
[MES-10320]: https://dvsa.atlassian.net/browse/MES-10320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10320: mobile build wf update

.github/actions/dms-functions/wait-for-replication-task/action.yaml
amend wait-for-replication-task action messages
Related issue: [MES-10320](https://dvsa.atlassian.net/browse/MES-10320)
[MES-10320]: https://dvsa.atlassian.net/browse/MES-10320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10320: amend wait-for-replication-task action messages

.github/workflows/deploy-backend.yaml
disable send teams notification for deploy backend wf
=> disable send teams notification for deploy backend wf

.github/workflows/publish-package.yaml
=> feat: point to npm

.github/workflows/deploy-backend-des.yaml, .github/workflows/release-manifest-des.yaml
update new deploy backend wf to skip API proxy build artefacts
Related issue: [MES-10383](https://dvsa.atlassian.net/browse/MES-10383)
[MES-10383]: https://dvsa.atlassian.net/browse/MES-10383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10383: update new deploy backend wf to skip API proxy build artefacts

.github/actions/git-functions/create-branches/action.yaml, .github/actions/git-functions/create-releases/action.yaml, .github/actions/git-functions/delete-branches/action.yaml, .github/actions/git-functions/delete-releases/action.yaml, .github/workflows/release-cut.yaml
fix issues with repositories.json loops
Related issue: [MES-10446](https://dvsa.atlassian.net/browse/MES-10446)
[MES-10446]: https://dvsa.atlassian.net/browse/MES-10446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10446: fix issues with repositories.json loops

.github/actions/git-functions/create-releases/action.yaml, .github/actions/git-functions/delete-releases/action.yaml
fix create-release and delete-release action
Related issue: [MES-10446](https://dvsa.atlassian.net/browse/MES-10446)
[MES-10446]: https://dvsa.atlassian.net/browse/MES-10446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10446: fix create-release and delete-release action

.github/workflows/undo-release-cut.yaml
=> MES-10448: fix delete command output

.github/workflows/deploy-backend.yaml
uncomment ms teams notification job for deploy backend wf
Related issue: [MES-10370](https://dvsa.atlassian.net/browse/MES-10370)
[MES-10370]: https://dvsa.atlassian.net/browse/MES-10370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10370: Deploy BE wf teams notification fix

.github/workflows/sonarqube-scan.yaml
Related issue: [MES-10445](https://dvsa.atlassian.net/browse/MES-10445)
[MES-10445]: https://dvsa.atlassian.net/browse/MES-10445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10445: update sonarqube scan wf permissions

.github/workflows/sonarqube-scan.yaml
update permissions for sonarqube wf
Related issue: [MES-10445](https://dvsa.atlassian.net/browse/MES-10445)
[MES-10445]: https://dvsa.atlassian.net/browse/MES-10445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10445: update permissions for sonarqube wf

.github/workflows/sonarqube-scan.yaml
revert update permissions for sonarqube wf
Related issue: [MES-10445](https://dvsa.atlassian.net/browse/MES-10445)
[MES-10445]: https://dvsa.atlassian.net/browse/MES-10445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MES-10445: revert update permissions for sonarqube wf

.github/workflows/release-manifest.yaml
Temporary fix using hard coded release branch 
Related issue: [MES-10604](https://dvsa.atlassian.net/browse/MES-10604)
[MES-10604]: https://dvsa.atlassian.net/browse/MES-10604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> temp hard code of release branch value

.github/workflows/release-manifest.yaml
Related issue: [MES-10606](https://dvsa.atlassian.net/browse/MES-10606)
[MES-10606]: https://dvsa.atlassian.net/browse/MES-10606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> removed branch reference
